export const enum GlobalActions {
    LOAD_SITE_INFO = 'GLOBAL/LOAD_SITE_INFO',
    LOAD_LINK_LIST = 'GLOBAL/LOAD_LINK_LIST',
    LOAD_SOCIAL_LIST = 'GLOBAL/LOAD_SOCIAL_LIST',
    LOAD_CATEGORY_LIST = 'GLOBAL/LOAD_CATEGORY_LIST',
    LOAD_ARTICLE_LIST = 'GLOBAL/LOAD_ARTICLE_LIST'
}
