export const enum GlobalMutations {
    UPDATE_SITE_INFO = 'GLOBAL/UPDATE_SITE_INFO',
    UPDATE_LINK_LIST = 'GLOBAL/UPDATE_LINK_LIST',
    UPDATE_SOCIAL_LIST = 'GLOBAL/UPDATE_SOCIAL_LIST',
    UPDATE_CATEGORY_LIST = 'GLOBAL/UPDATE_CATEGORY_LIST',
    UPDATE_FILTER = 'GLOBAL/UPDATE_FILTER',
    UPDATE_ARTICLE_LIST = 'GLOBAL/UPDATE_ARTICLE_LIST',
    UPDATE_CURRENT_ARTICLE_LIST = 'GLOBAL/UPDATE_CURRENT_ARTICLE_LIST',
    UPDATE_CURRENT_PAGE = 'GLOBAL/UPDATE_CURRENT_PAGE',
    UPDATE_CURRENT_LIMIT = 'GLOBAL/UPDATE_CURRENT_LIMIT'
}
